# generated by datamodel-codegen:
#   filename:  workdir/modelplane_ai_v1alpha1_modelendpoint.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, constr

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class Api(BaseModel):
    prefix: constr(min_length=1, max_length=512) | None = '/v1'
    """
    The path the backend serves that API under: /v1 for most, /openai/v1 for Groq, and a per-replica path for a Modelplane-composed endpoint, whose cluster gateway distinguishes replicas by path.
    """
    schema_: Literal['OpenAI', 'Anthropic'] | None = Field('OpenAI', alias='schema')
    """
    The API the backend speaks. A gateway translates between this and whatever the caller sent, so an OpenAI client can reach an Anthropic backend and the reverse.
    """


class CredentialRef(BaseModel):
    key: constr(min_length=1, max_length=253) | None = 'apiKey'
    """
    The Secret key holding the credential.
    """
    name: constr(min_length=1, max_length=253)
    """
    Secret in this ModelEndpoint's namespace, with the credential under the key named by key.
    """


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Spec(BaseModel):
    api: Api | None = None
    """
    The API this backend speaks, and where it serves it. Defaults to the OpenAI API under /v1, which is what most providers and every Modelplane-composed endpoint serve.
    """
    credentialRef: CredentialRef | None = None
    """
    Secret holding this backend's credential, which the gateway attaches on the way out. The credential never reaches the caller, and the caller's own credential never reaches the backend. An endpoint whose Secret is missing carries no traffic and says so in its conditions.
    """
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    model: constr(min_length=1, max_length=253) | None = None
    """
    The name this backend knows the model by, which a gateway rewrites the request's model to on the way out. Unset, the caller's model name passes through unchanged.
    A caller names a ModelService and gets back whichever model actually served, the way asking OpenAI for gpt-4o returns gpt-4o-2024-08-06.
    """
    origin: constr(min_length=1, max_length=2048)
    """
    Scheme and host of the backend, with no path: an https origin gets TLS originated to it. A port is only needed for a non-default one.
    The host must be a name, never an address. Envoy AI Gateway applies per-backend model rewriting, credentials and priority failover only when every backend in a route is addressed by hostname; given an address it keeps passing traffic but silently stops applying them, which would send a caller's own model name to a provider with no credential attached.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """


class ModelEndpoint(BaseModel):
    apiVersion: Literal['modelplane.ai/v1alpha1'] | None = 'modelplane.ai/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['ModelEndpoint'] | None = 'ModelEndpoint'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    status: Status | None = None


class ModelEndpointList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[ModelEndpoint]
    """
    List of modelendpoints. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """