# generated by datamodel-codegen:
#   filename:  workdir/infrastructure_modelplane_ai_v1alpha1_servingstack.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, conint, constr

from .....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class ClientCA(BaseModel):
    certificate: constr(min_length=1, max_length=16384)
    """
    The CA certificate, PEM encoded.
    """
    name: constr(min_length=1, max_length=253)
    """
    The InferenceGateway this CA belongs to.
    """


class Listener(BaseModel):
    name: constr(min_length=1, max_length=63)
    """
    Unique listener name.
    """
    port: conint(ge=1, le=65535)
    """
    Port number for this listener.
    """
    protocol: Literal['HTTP', 'TCP']
    """
    Protocol for this listener.
    """


class Gateway(BaseModel):
    className: constr(min_length=1, max_length=63) | None = 'envoy'
    """
    GatewayClass name. Override if the cluster already has a GatewayClass named envoy.
    """
    clientCAs: list[ClientCA] | None = Field(None, max_length=32)
    """
    PEM certificates of the CAs whose client certificates this gateway accepts, one per InferenceGateway in the fleet. Projected from the InferenceCluster, which reads them from each gateway's status.
    Presenting one of these is how a caller proves it is a fleet gateway. Requests without one are refused, which is what makes a fleet gateway the only thing that can reach the engines behind this cluster's gateway.
    """
    hostname: constr(min_length=1, max_length=253) | None = None
    """
    The name this cluster's gateway is reached by, projected from the InferenceCluster. The gateway serves a certificate for it, so an InferenceGateway can originate TLS and know it reached the right cluster. Without it the gateway serves plain HTTP and carries no traffic, since an InferenceGateway addresses a cluster by name.
    """
    listeners: list[Listener] | None = Field(None, max_length=8)
    """
    Gateway listeners. Defaults to a single HTTP listener on port 80 if not specified.
    """


class Secret(BaseModel):
    key: constr(max_length=253)
    """
    Key within the Secret that holds the credential data.
    """
    name: constr(max_length=253)
    """
    Name of the Secret.
    """
    namespace: constr(max_length=253) | None = None
    """
    Namespace of the Secret, when it isn't this ServingStack's namespace. Set on cloud identity entries whose credential is the Secret the cloud provider's ProviderConfig references.
    """
    type: Literal[
        'Kubeconfig',
        'GoogleApplicationCredentials',
        'AWSWebIdentityCredentials',
        'NebiusServiceAccountCredentials',
    ]
    """
    The type of credential this secret contains. Kubeconfig is required. Any other value is a cloud identity type; when present, the serving stack authenticates to the cluster as that identity instead of using the kubeconfig's embedded credentials.
    """


class Spec(BaseModel):
    cloud: Literal['GKE', 'EKS', 'AKS', 'Nebius', 'Vultr', 'Existing']
    """
    The cloud the target cluster runs on. Selects the fixed set of components and versions this stack installs there, which is resolved per cloud at build time and changes only with a Modelplane release. Mirrors InferenceCluster.spec.cluster.source; the cluster composition sets it.
    """
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    gateway: Gateway | None = None
    """
    Configuration for the cluster's inference traffic gateway.
    """
    secrets: list[Secret] = Field(..., max_length=8, min_length=1)
    """
    Secrets used to authenticate to the target cluster. Typically sourced from a GKECluster's status.secrets. Secrets are in the same namespace as this ServingStack unless an entry says otherwise. A Kubeconfig secret is required. If a cloud identity secret is present, the serving stack authenticates as that identity instead of relying on the kubeconfig's embedded credentials.
    """
    stack: Literal['Standard', 'Dynamo'] | None = 'Standard'
    """
    Which serving stack this installs. Standard (the default) is the Modelplane-composed serving layer: a Deployment or LeaderWorkerSet, Gateway API, and the endpoint picker. Dynamo swaps in NVIDIA's components: Grove with the KAI Scheduler for multi-node gang scheduling, and a shared ModelExpress server for weight distribution. Propagated from the InferenceCluster.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class GatewayModel(BaseModel):
    address: constr(max_length=256) | None = None
    """
    The gateway's external address, once assigned by the cloud load balancer.
    """
    caCertificate: constr(max_length=16384) | None = None
    """
    PEM certificate of the CA that signed this gateway's serving certificate. An InferenceGateway validates the gateway against it, so it reaches the cluster it meant to and not whatever answers on that address.
    """


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    gateway: GatewayModel | None = None
    """
    Status of the cluster's inference gateway.
    """


class ServingStack(BaseModel):
    apiVersion: Literal['infrastructure.modelplane.ai/v1alpha1'] | None = (
        'infrastructure.modelplane.ai/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['ServingStack'] | None = 'ServingStack'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    ServingStackSpec defines the desired state of ServingStack.
    """
    status: Status | None = None
    """
    ServingStackStatus defines the observed state of ServingStack.
    """


class ServingStackList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[ServingStack]
    """
    List of servingstacks. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """