# generated by datamodel-codegen:
#   filename:  workdir/modelplane_ai_v1alpha1_modelroute.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, conint, constr

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Selector(BaseModel):
    matchLabels: dict[str, constr(max_length=63)] = Field(
        ..., max_length=16, min_length=1
    )


class Endpoint(BaseModel):
    priority: conint(ge=0, le=63) | None = 0
    """
    Lower is preferred. Entries at the same priority share traffic by weight; a higher number is only tried when nothing below it has a healthy endpoint.
    """
    selector: Selector
    """
    Selects ModelEndpoints in this route's namespace.
    """
    weight: conint(ge=1, le=1000000) | None = 1
    """
    Share of traffic for this entry relative to the other entries at the same priority, spread as evenly as possible across the endpoints it matches.
    """


class Spec(BaseModel):
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    endpoints: list[Endpoint] = Field(..., max_length=32, min_length=1)
    """
    A priority order over ModelEndpoints, each entry selecting a set of them by label. A verbatim copy of the ModelService's spec.endpoints.
    """
    gatewayName: constr(min_length=1, max_length=253)
    """
    Name of the InferenceGateway this route is pinned to. The function resolves the gateway's cluster, its ProviderConfig and its address from here, and renders onto that cluster.
    """
    serviceName: constr(min_length=1, max_length=253)
    """
    Name of the ModelService this route belongs to. With the ModelRoute's own namespace it derives the composed object names and the model name a caller passes (<namespace>/<service>), so the service and its routes agree on both.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Endpoints(BaseModel):
    ready: int | None = None
    total: int | None = None


class Status(BaseModel):
    address: str | None = None
    """
    External address of the gateway this route is on.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    endpoints: Endpoints | None = None
    """
    Observed endpoint counts for this route, across all priorities.
    """
    hostname: str | None = None
    """
    The name that gateway answers on, if it has one.
    """
    model: str | None = None
    """
    The name a caller passes as the request's model, <namespace>/<service>.
    """


class ModelRoute(BaseModel):
    apiVersion: Literal['modelplane.ai/v1alpha1'] | None = 'modelplane.ai/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['ModelRoute'] | None = 'ModelRoute'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    status: Status | None = None


class ModelRouteList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[ModelRoute]
    """
    List of modelroutes. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """